### ISSUE TITLE
This is totally barked, they closed the www2 API

### ISSUE THREAD

**Issue by mvcaaa** [ojarva/python-helen-electricity-usage#4]
![image](https://user-images.githubusercontent.com/1244503/139729935-3decc956-7c7d-421d-afa2-7d762270b62f.png)

Any plans to fix it ? Do you need any help on that ?
I can try to investigate/track requests to the new APIs.

Also, I think this is a good base for a new HomeAssistant integration https://www.home-assistant.io/integrations/#search/helen

**Comment by ojarva** [comment]
That's unfortunate. I use this with my own things. I don't use
homeassistant and I have no plans to build any integrations for it either.

I'll take a look on the new APIs they have but it's somewhat likely new
ones will be harder to work with.

**Comment by Janska85** [comment]
I took a stab at this and was able to pull some data out from Helen using the code in #5.

If my solution pleases you feel free to use it as you see fit :)

**Comment by ojarva** [comment]
Should be fixed now in #5 , I hope.
